services:
  - type: web
    name: evaluacion-alternativas-producto
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run my_app/Inicio.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
